# Generated by Django 4.0.1 on 2022-02-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
