# Generated by Django 4.0.1 on 2022-02-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_jobs_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contribution',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
