# Generated by Django 4.0.1 on 2022-03-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_jobs_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
