# Generated by Django 4.0.1 on 2022-02-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_alter_contract_end_date_alter_contract_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
