# Generated by Django 4.0.1 on 2022-02-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_alter_bids_bid_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='subbmitted',
            new_name='submitted',
        ),
    ]
