# Generated by Django 4.0.1 on 2022-02-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_rename_subbmitted_contract_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='contribution',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
